apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  namespace: default
spec:
  selector:
    matchLabels:
      name: gateway
  replicas: 2
  template: 
    metadata:
      labels:
        name: gateway
    spec:
      containers:
      - name: gateway
        image: dattritat/gateway:v0.2
        ports: 
        - containerPort: 8080