apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: default
spec:
  selector:
    matchLabels:
      name: user-service
  replicas: 2
  template: 
    metadata:
      labels:
        name: user-service
    spec:
      containers:
      - name: user-service
        image: dattritat/user-service:v0.1
         env:
        - name: MYSQL_HOST
          value: "34.168.43.245"   
        ports: 
        - containerPort: 8081