apiVersion: apps/v1
kind: Deployment
metadata:
  name: business-service
  namespace: default
spec:
  selector:
    matchLabels:
      name: business-service
  replicas: 2
  template: 
    metadata:
      labels:
        name: business-service
    spec:
      containers:
      - name: gateway
        image: dattritat/business-service:v0.1
        ports: 
        - containerPort: 8082